definitions:
  payload.SignInBody:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: The API Server of Codern
  title: Codern API Server
  version: 0.0.0
paths:
  /api/auth/google:
    get:
      description: Get an url to signin with the Google account
      produces:
      - application/json
      responses: {}
      summary: Get Google auth URL
      tags:
      - auth
  /api/auth/google/callback:
    get:
      description: A callback route for Google OAuth to redirect to after signing
        in
      produces:
      - application/json
      responses: {}
      summary: Sign in with Google
      tags:
      - auth
  /api/auth/me:
    get:
      consumes:
      - application/json
      description: Get an authenticated user data
      parameters:
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get an user data
      tags:
      - auth
  /api/auth/signin:
    post:
      consumes:
      - application/json
      description: Sign in with email & password provided by the user
      parameters:
      - description: Email and password for authentication
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/payload.SignInBody'
      produces:
      - application/json
      responses: {}
      summary: Sign in with self provider
      tags:
      - auth
  /api/auth/signout:
    get:
      description: Sign out and remove a sid cookie header
      parameters:
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuths: []
      summary: Sign out
      tags:
      - auth
  /api/workspaces:
    get:
      consumes:
      - application/json
      description: Get all workspaces
      parameters:
      - collectionFormat: csv
        description: Specific fields to include in the response
        in: query
        items:
          enum:
          - participants
          type: string
        name: fields
        type: array
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: List workspaces
      tags:
      - workspace
  /api/workspaces/{workspaceId}:
    get:
      consumes:
      - application/json
      description: Get a workspace from workspace id on path parameter
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: integer
      - collectionFormat: csv
        description: Specific fields to include in the response
        in: query
        items:
          enum:
          - participants
          type: string
        name: fields
        type: array
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get a workspace
      tags:
      - workspace
  /api/workspaces/{workspaceId}/assignments:
    get:
      consumes:
      - application/json
      description: Get all assignment from a workspace id on path parameter
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: integer
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: List assignment
      tags:
      - workspace
  /api/workspaces/{workspaceId}/assignments/{assignmentId}:
    get:
      consumes:
      - application/json
      description: Get an assignment from workspace id on path parameter
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: integer
      - description: Assignment ID
        in: path
        name: assignmentId
        required: true
        type: integer
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get an assignment
      tags:
      - workspace
  /api/workspaces/{workspaceId}/assignments/{assignmentId}/submissions:
    get:
      consumes:
      - application/json
      description: Get all submission from a workspace id on path parameter
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: integer
      - description: Assignment ID
        in: path
        name: assignmentId
        required: true
        type: integer
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: List submission
      tags:
      - workspace
    post:
      consumes:
      - application/json
      description: Submit a submission of the assignment
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: integer
      - description: Assignment ID
        in: path
        name: assignmentId
        required: true
        type: integer
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Create a new submission
      tags:
      - workspace
  /file/user/{userId}/profile:
    get:
      description: Get an user profile image from internal file system by proxy
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - image/png
      - image/jpeg
      - image/gif
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get an user profile image
      tags:
      - file
  /file/workspaces/{workspaceId}/assignments/{assignmentId}/detail:
    get:
      description: Get a workspace detail markdown from internal file system by proxy
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: number
      - description: Assignment ID
        in: path
        name: assignmentId
        required: true
        type: number
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - image/png
      - image/jpeg
      - image/gif
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get a workspace detail markdown
      tags:
      - file
  /file/workspaces/{workspaceId}/profile:
    get:
      description: Get a workspace profile image from internal file system by proxy
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: number
      - description: Session ID
        in: header
        name: sid
        required: true
        type: string
      produces:
      - image/png
      - image/jpeg
      - image/gif
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get a workspace profile image
      tags:
      - file
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
